### ISSUE TITLE
Make AutoExampleDriver available

### ISSUE THREAD

**Issue by alisey** [wix/wix-ui#104]
In the pagination e2e we would like to reuse the same example in the storybook for multiple tests.

**Comment by shlomitc** [comment]
We suggest using the `AutoDocs` tool.
It allows you not only to document easily but also to test components that changes props dynamically.

Docs are a little bit outdated, but https://github.com/wix/wix-style-react/blob/master/docs/AutoDocs.md

Usage example:
https://github.com/wix/wix-ui-backoffice/blob/master/stories/CounterBadge/index.tsx#L7

Testing example:
https://github.com/wix/wix-ui-backoffice/blob/master/src/components/CounterBadge/CounterBadge.e2e.ts
