### ISSUE TITLE
wix-storybook-utils: API tab - Need to be able to remove methods from "Available Methods"

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#1046]
The "Available Methods" section shows all member methods.

It shows also some methods that are meant to be internal.
JavaScript has no private method mechanism for classes.

Need a way to hide those methods from the docs.

Maybe using JSDoc tags?
We can use [`@ignore`](http://usejsdoc.org/tags-ignore.html)
Or [`@private`](http://usejsdoc.org/tags-private.html) 

@argshook

**Comment by argshook** [comment]
Currently methods starting with underscore are considered private and wont show up, for example `_imPrivate`
