### ISSUE TITLE
Need to have good changing background color 

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-ui#106]
When selecting components with light background or text color, we need to be able to detect that and change the bacground of the box in the story,
If not automatically than at least let's give the users a way to change it manually

![image](https://user-images.githubusercontent.com/18248989/34373152-2eefde42-eae2-11e7-8699-eac69be4c227.png)

**Comment by argshook** [comment]
maybe let's just have darker checkerboard pattern or some button that changes background manually. I don't know of a solid way to automatically determine contrast. canvas stuff would seem too heavy for now

**Comment by lbelinsk** [comment]
manually is sufficient for now, and if we want in the future we can always improve, really not that important.

**Comment by shlomitc** [comment]
Just a simple switch between black/white/transparent

**Comment by argshook** [comment]
FYI 
![screenshot 2018-01-05 09 21 02](https://user-images.githubusercontent.com/4284659/34599253-d18c8b14-f1f9-11e7-801b-3bb36c2b4105.png)
