### ISSUE TITLE
wix-storybook-utils: Need to be able to use JSDoc for prop types

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#1060]
In WSR we started using custom Validators.
In such case AutoDocs would not be able to determine the prop type.

Example:
https://github.com/wix/wix-style-react/blob/9873611bf9f754747cf7ee2b767f4527d825d053/src/Button/index.js#L12

Suggestion:
Add support for JSDocs with tags:
`@type`

**Comment by argshook** [comment]
> In WSR we started using custom Validators.

:) started? watch [this](https://github.com/wix/wix-style-react/blob/master/src/Composite/CompositeValidation.js) (which should be eradicated imo)

---

in example you linked it was solved simply with `componentPath: '../../src/Button/Button.js'`. as in, giving direct path to implementation which does not include custom validation like that.

maybe your case can be solved like that too?

**Comment by argshook** [comment]
closing in favor of https://github.com/wix-private/wix-style-react-playground/issues/34
