### ISSUE TITLE
wix-storybook-utils: ReactLive - Issues

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#1061]
## We can not show imports

ReactLive does not support imports in LiveEditor.
So we can not display the relevant imports for the example.

### Solution
Maybe we can display a separate Code block (outside of the LiveEditor) which displays only the imports section.
And make it so that the "copy to clipboard" button, will concatenate the import section with the code.

## No support for class members
Can not use anonymous function members.
```js
class Component  {
  someVar = 1;
  handleChange = (event) => {};
}
```
We need to do :
```js
class Component  {
  constructor(props) {
    this.someVar = 1;
    this.handleChange = this.handleChange.bind(this);

  }
  handleChange(event){};
}
```

## Can not use imports

The motivation is to have a valid js file (with js extension, `Example.js`), that the IDE can lint and auto-format. And we even can render in a page without the ReactLive.
For that we need to use imports.
ReactLive does not support imports.

Also If we use calsses, so we can't use autoRender (`noInline`), and we need to have a `render()` function in the code.

#### Solution
- Process (parse) the Example file and remove `import` (and `export`) statements.
- Append a `render()` to the example file.

**Comment by argshook** [comment]
this issue consists of two issues:

1. Can not use/show imports  
   fixed by https://github.com/wix-private/wix-style-react-playground/issues/35
1. No support for class members
   moved to https://github.com/wix-private/wix-style-react-playground/issues/37

one is fixed, another is extracted, so closing this one.
