### ISSUE TITLE
wix-storybook-utils: `<Playground/>` - should allow full width preview

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#1065]
For components like Page, Grid.
Also see [CalendarPanel](https://wix-wix-style-react.surge.sh/?selectedKind=WIP&selectedStory=CalendarPanel&full=0&addons=0&stories=1&panelRight=0)

Probably need to put controls above or below?

Maybe we also want to make the whole "controls" section narrower (more compact)

Or make a toggle for showing controls or not?

@milkyfruit ?

**Comment by milkyfruit** [comment]
@hepiyellow Narrowed options is a partial solution.
To make it fully responsive we need to allow show/hide controls.
If they overlap, they should go above.

**Comment by hepiyellow** [comment]
@argshook Are you in sync with this?

**Comment by argshook** [comment]
for cases like this `code` section should be used. Closing as (i think) this issue was opened before `code` section existed
