### ISSUE TITLE
Allow to control the children prop when it is of type text in the storybook

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-ui#107]
For example, Button, badge have text children, we would like to have a way to type their text content

**Comment by argshook** [comment]
didn't check but im guessing it's `children: PropTypes.node`? if so, you can use `exampleProps`:
```
exampleProps: {
  children: [ 'Hello', 'Hello Again', <span>And here too!</span>]
}
```

with `node` a lot more than `string` can be used, so in such case i no longer show input for text and expect predefined list of example nodes.

Maybe, as idea, i could `if exampleProps.children then displayThem() else displayInput()`

**Comment by lbelinsk** [comment]
I think it is even `any`, not `node`.
