### ISSUE TITLE
Don't show some props in the auto examples

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-ui#111]
We might want to hide   `data-class`, `dataHook`, `id` props

**Comment by argshook** [comment]
no, why?

**Comment by lbelinsk** [comment]
What does it give for the user?
He has the "API" tab to see the prop list, this one is not helping and just adds noise there imo.

**Comment by argshook** [comment]
and this is good, if it's noise then maybe the prop is not that useful afterall. I think in the end the idea is to merge "API" and "Interactive Props" into one list

**Comment by shlomitc** [comment]
`id `should be there as it is part of the component api.

any `data-` attributes should not be displayed as they are customized by the user. anyway, I think it shouldn't be an issue for stylable components as they don't declare it.
