### ISSUE TITLE
data-hook is hashed

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#1111]
This was reported by a consumer,
he sent me a DOM snapshot with this attribute on the (wix-ui-backoffice) `<Badge/>` component.
```
<div 
  data-badge2684491952-data-hook="recovery-badge-0" 
  data-badge2684491952-type="solid"
  ...
```

This means that the `style()` method adds a hash to `data-*` props.
As If something change in Stylable, since it didn't use to dod that before.

Needs investigation.

**Comment by hepiyellow** [comment]
@barak007 Can you explain this theoretically?
(Sorry for not having yet a reproducible case)

**Comment by argshook** [comment]
no longer relevant for long time, closing
