### ISSUE TITLE
wix-storybook-utils (LiveCodeExample) - playground breaks under some conditions

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-ui#1139]
You start with something simple
![image](https://user-images.githubusercontent.com/6093192/52865336-149f4f00-3145-11e9-8a94-c9e989ef1f6d.png)

Then you start typing and changing prop like `style` and you get this error:
![image](https://user-images.githubusercontent.com/6093192/52865409-3d274900-3145-11e9-9d33-ba4ebd0d6ae9.png)

The playground breaks and is not responsive anymore.

1. try solving this issue
2. make `reset` actually reset the component, (rerender by passing a new `key`?)

**Comment by argshook** [comment]
fixed in #1152
