### ISSUE TITLE
wix-storybook-utils (LiveCodeExample) - title and button looks broken when not enough space

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-ui#1140]
![image](https://user-images.githubusercontent.com/6093192/52865547-8d061000-3145-11e9-872d-99c30c449762.png)

**Comment by argshook** [comment]
this component has been updated to look in sync with UX, issue no longer relevant

![2019-02-24-172457_screenshot](https://user-images.githubusercontent.com/4284659/53301254-21185b80-3859-11e9-8a81-56c510afc030.png)
