### ISSUE TITLE
wix-ui-core: the .story.tsx files that are in src are published to NPM

### ISSUE THREAD

**Issue by boriskor** [wix/wix-ui#1199]
For example, [wix-ui-core/src/components/avatar/avatar.story.tsx](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/avatar/avatar.story.tsx). We need to exclude all the files that are not relevant to the source code from publishing to NPM.

**Comment by argshook** [comment]
the weight of story files in npm tarball is neglible, will leave it for now
