### ISSUE TITLE
wix-storybook-utils: `code` section - add `noPadding` and `backgroundColor` props

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#1202]
### noPadding

`noPadding` prop will render the component in the Preview, without any padding.
This is useful for the `<Page/>` component, in which it shuold takes the whole preview area, so it is easy to "see" the borders of the page, the page has it's own padding. 

### backgroundColor
The default backgroundColor of the `code` section is the same color as the `<Page/>`'s.
Having the ability to control the background color could:
- be an alternative to using `noPadding` with `<Page/>` component
- Could be used to have a `white` background for components which are supposed to be inside `<Card/>` component (form components)

> Maybe we should simply add a `previewClassName` prop

@argshook FYI

**Comment by argshook** [comment]
no longer relevant, `code` section design has changed
