### ISSUE TITLE
`componentProps` should work with `PropTypes.number`

### ISSUE THREAD

**Issue by argshook** [wix/wix-ui#123]
currently it works but the value is a string, which yields error in console and potentialy could break some component. Currently `<Input/>` is used within interactive props, it should be something like `<Input type="number"/>` (which doesn't exist atm).

**Comment by shlomitc** [comment]
is this one still relevant?

**Comment by argshook** [comment]
yes, should be quick to fix though

**Comment by argshook** [comment]
in progress #940
