### ISSUE TITLE
wix-ui-core: Popover (tests) - In JSDom test, mouseEnter event is not propagated to root element

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#1271]
## Suddenly
Suddenly the `wix-ui-core` [build broke](https://tc.dev.wixpress.com/viewLog.html?buildId=86483840&buildTypeId=WixUi_Packages_WixUiCore).

## Analysis
- Popover.uni.driver's `mouseEnter()` is triggering `MouseEnter ` event on the `<div data-hook="popover.element"/>`, and it doesn't propagate (bubble) to the `onMouseEnter` listener which is on the Popover's root element.
- In browser, the propagation is working proparely.
- I couldn't find which dependency caused the change in behaviour.

## Solution (Urgent)

Make the `Popover.uni.driver` trigger the `MouseEnter` event on the root element. (this [commit](https://github.com/wix/wix-ui/commit/f4d6f15b1d2688ff2f2932c339210e1be03c334b) fixes it)

The legacy `Popover.dirver` is already triggering the event on the root element.

## TODO

Investigate wheat broke the propagation behavior, it could be happening in other projects as well.

**Comment by mykas** [comment]
Not relevant anymore.
