### ISSUE TITLE
`<Popover/>` - the onClickOutside wrapper sometimes throws errors on not able to find the DOM node

### ISSUE THREAD

**Issue by mykas** [wix/wix-ui#1437]
The issues happens only on certain conditions and its pretty hard to reproduce it except in one of our projects. The react version use: 16.8.6. The method that fails is this:https://github.com/Pomax/react-onclickoutside/blob/master/src/index.js#L100 . 

Issue opened: https://github.com/Pomax/react-onclickoutside/issues/328

**Comment by shlomitc** [comment]
@mosheKerbel - I think we already saw something about this when migrating WSR from React15 to 16. do you remember?

**Comment by mykas** [comment]
But it works on React 16.9 because Dan from Facebook already did a workaround I guess, but anyway this is something we must fix. I am not convinced that the guy from react-onclickoutside will fix it as his codebase depends on it.

**Comment by mykas** [comment]
It seems that user reported issues is related to React.Suspense and this is directly React bug before React 16.9.0

**Comment by EgoziE** [comment]
WSR v9 doesn't use `react-onclickoutside` anymore.
Closing this issue.
