### ISSUE TITLE
[WSR-types] Wrong DataTableColumn types 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-ui#1666]
wsr-types declaration:

![image](https://user-images.githubusercontent.com/8848858/70788619-f5d80c00-1d99-11ea-884e-357449dcfa8c.png)

WSR docs for this component:
https://wix-style-react.now.sh/?selectedKind=Deprecated&selectedStory=DataTable%20%28Legacy%29&full=0&addons=0&stories=1&panelRight=0

![image](https://user-images.githubusercontent.com/8848858/70788642-05575500-1d9a-11ea-8664-72d6632650e3.png)

**Comment by giladsegal** [comment]
Fixed at #1670
