### ISSUE TITLE
Missed prop in <ModalSelectorLayout /> typing 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-ui#1667]
`disableConfirmation` prop is missing in `wsr-types`:

Docs describes this prop:
https://wix-style-react.now.sh/?activeTab=API&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=ModalSelectorLayout&stories=1

But typing doesn't have:
https://github.com/wix/wix-ui/blob/master/packages/wsr-types/src/components/ModalSelectorLayout.d.ts#L17

![image](https://user-images.githubusercontent.com/8848858/70795604-d98f9b80-1da8-11ea-8df3-081b8157374d.png)

**Comment by giladsegal** [comment]
Duplicates #1669
