### ISSUE TITLE
Types <FloatingNotification /> textButtonProps is so strict

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-ui#1668]
We want to pass `target` props as well, but wsr-types is defined limit of prop which we can pass to as `textButtonProps`:

![image](https://user-images.githubusercontent.com/8848858/70797202-b109a080-1dac-11ea-943c-104ed1c6f42e.png)

![image](https://user-images.githubusercontent.com/8848858/70797222-bb2b9f00-1dac-11ea-8766-49421f3744b3.png)

WSR docs for this component:
https://wix-style-react.now.sh/?activeTab=API&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=FloatingNotification&stories=1

**Comment by giladsegal** [comment]
Fixed at #1670
