### ISSUE TITLE
`ModalSelectorLayout` types have mistakes  

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-ui#1669]
Couple issues:

1. `disableConfirmation` prop for `ModalSelectorLayout` is missing, but described in docs and works well.
Story: https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=ModalSelectorLayout&full=0&addons=0&stories=1&panelRight=0
![image](https://user-images.githubusercontent.com/8848858/70819460-fa72e380-1dde-11ea-9363-f49402c12cac.png)

2. Relates to https://github.com/wix/wix-style-react/issues/4704 `title` prop should be `ReactNode`.
<img width="366" alt="Screen Shot 2019-12-13 at 19 32 14" src="https://user-images.githubusercontent.com/8848858/70819631-62c1c500-1ddf-11ea-85cf-563c3b823d95.png">

**Comment by rudnitskih** [comment]
FYI @brumeregan

**Comment by giladsegal** [comment]
Fixed at #1670
