### ISSUE TITLE
`ModalSelectorLayoutCommonProps` has non optional prop.

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-ui#1672]
https://wix-style-react.now.sh/?activeTab=API&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=ModalSelectorLayout&stories=1

`emptyState` should be optional in props. 

![image](https://user-images.githubusercontent.com/8848858/70908793-65553200-200c-11ea-91bc-4151822dad1a.png)

![image](https://user-images.githubusercontent.com/8848858/70908828-74d47b00-200c-11ea-989b-db9c221907cd.png)

Relates to #1669

**Comment by giladsegal** [comment]
Actually it's required in the PropTypes but also has defaultProp :(
I will fix the types

**Comment by giladsegal** [comment]
Fixed https://github.com/wix/wix-ui/pull/1674

**Comment by rudnitskih** [comment]
@giladsegal Thank you for the quick fix!
