### ISSUE TITLE
wix-ui-core: stylable-intergraton should be a dev dependency

### ISSUE THREAD

**Issue by AviVahl** [wix/wix-ui#181]
`stylable-integration` is a build-time integration library. It should not be required for runtime.
Would it be possible to move it to devDependencies?

Otherwise, projects without webpack (that use wix-ui-core directly or indirectly) get warnings such as:
`warning "wix-ui-core > stylable-integration > file-loader@1.1.6" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0"`

**Comment by shlomitc** [comment]
Fixed
