### ISSUE TITLE
wix-ui-framework(feature request) - allow replacing variables in stylable files

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-ui#1956]
it would make a lot of sense to replace variables also in the stylable files.
For example, in the `wix-ui-tpa` project I'd like to do the following:

```css
:import {
  -st-from: "../{%ComponentName}.st.css";
  -st-default: {%ComponentName};
}

.root {
  -st-mixin: {%ComponentName}(
    BgColor: ''"color(--myBackgroundOverride)"''
  );
}
```

@argshook - WDYT?

**Comment by argshook** [comment]
This already works, no changes needed for `wuf`

the only difference from your example is the syntax. `wuf` internally
uses [ejs](https://ejs.co/), so it should be like so:

```
:import {
  -st-from: "../<%= ComponentName %>.st.css";
  -st-default: <%= ComponentName %>;
}

.root {
  -st-mixin: <%= ComponentName %>(
    BgColor: ''"color(--myBackgroundOverride)"''
  );
}
```

---

there are more options available in the template files, like some
utilities to switch between kebab-case or snake_case etc.

i thought it's documented but apparently not, i'll make sure it gets
more docs

**Comment by shlomitc** [comment]
coolness!

**Comment by argshook** [comment]
@shlomitc just fyi, added some examples here https://github.com/wix/wix-ui/blob/master/packages/wix-ui-framework/docs/generate.md#using-ejs-in-template-files

**Comment by shlomitc** [comment]
looks good
