### ISSUE TITLE
Make wix-eventually public and use it in tests instead of setTimeout

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-ui#26]

**Comment by viliusl** [comment]
@lbelinsk @argshook @shlomitc - I can, but I'm not sure I want to publish another me-too promise retrying library:
 - there is a plus that for internal projects that use `wix-eventually` it would be seamless to migrate;
 - `wix-eventually` works well for tests and usually have defaults that work for us.

There are libs that are really close:
 - https://github.com/rstacruz/mocha-eventually/blob/master/README.md - it's just a bit annoying that it's bound to `mocha` and is doing some not-great things under the hood;
 - https://www.npmjs.com/package/retry-as-promised - defaults are not great, need adapter/confiuration;
 - bunch of others - https://www.npmjs.com/search?q=retry+promise

So check it out and tell me if you want me to oss `wix-eventually` or you are good to go with one of those.

**Comment by viliusl** [comment]
https://www.npmjs.com/package/wix-eventually

**Comment by lbelinsk** [comment]
You were quicker than me. went looking if we have some open source thing that we can use to prevent your effort, and @felixmosh told me there is a good package out there, not sure which one. well, we have our wix-eventually, that can only help :). thanks!

**Comment by viliusl** [comment]
@lbelinsk - https://github.com/rstacruz/mocha-eventually is nice execpt it's not. For one it's bound to mocha in not-so-great-ways, ex. https://github.com/rstacruz/mocha-eventually/blob/master/index.js#L20. Others are meant more for production with strategies for retries, delays, etc.

If you find one just let me know - I can de-OSS it.

**Comment by felixmosh** [comment]
@lbelinsk, the better method is usage of [setImmediate](https://nodejs.org/api/timers.html#timers_setimmediate_callback_args) with promise, something like that.
https://github.com/mvila/set-immediate-promise/blob/master/src/index.js
