### ISSUE TITLE
Fix RadioButton

### ISSUE THREAD

**Issue by liorzisman** [wix/wix-ui#262]
Taken from checkbox issues as requested by Ido.
Will fix what is relevant and then provide for review.

TypeScript:
- [x] onChange has a combined type of all even handlers- bad. specific events have specific event flags
- [x] Props should extend the relevant native HTMLInput attributes interface. e.g. React.InputHTMLAttributes<HTMLInputElement> - Adding this type made storybook explode as the root is a div and not an input. the auto generate story is a problem.

Generally:
- [x] Meanwhile, if deciding to use propTypes, they should correctly reflect the typescript props interface (e.g. `aria-controls` that is string[] and not just array)
- [x] file names and folders should be lowercase kebab-case
- [x] () => { }, either use _.noop or create a common one in project.

Tests:
- [x] we should talk about using stylable DOMUtil exclusively to target internal DOM  parts in tests (instead of data-hook attributes). Two patterns to do the same thing. Currently it seems that both patterns are used...
- [x] test description should reflect the actual behavior - "Renders with default values" could have been "should be unchecked by default"

Aesthetically:
- [x] constructor is not needed. state & id can be initialized as fields.
- [x] render should be marked as public
- [x] components commons should be defined lower in class body (easier reading)

**Comment by shlomitc** [comment]
@liorzisman - is this issue done?
