### ISSUE TITLE
wix-storybook-utils: import example should support named import

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-ui#263]
![image](https://user-images.githubusercontent.com/6093192/36541045-4aa1fe56-17e5-11e8-9264-bc326e95332c.png)

should be `import {Input} from 'wix-ui-core/Input`

**Comment by argshook** [comment]
Isn't it a little weird that you do `from 'wix-style-react/Input';` but also have to destructure `{Input}`?

**Comment by shlomitc** [comment]
If tree shaking worked, I would just import from `wix-style-react` and I will destructure it anyway

**Comment by shlomitc** [comment]
Fixed
