### ISSUE TITLE
wix-ui-core: createHOC - shouldn't it also update when componentDidUpdate()

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#300]
Currently we update the dataHook only [`componentDidMount()`](https://github.com/wix/wix-ui/blob/988f4a30fe573aa89b5453f9adafbb763d66e760/packages/wix-ui-core/src/createHOC/index.tsx#L25)

I think we should also update it when `componentDidUpdate()`.

**Comment by shlomitc** [comment]
Why?

**Comment by hepiyellow** [comment]
I thought is it obvious.
If the component is re-rendered with different props,
and the `dataHook` value is different,
React may decide to update the DOM element instead of re-mounting it.
In that case `componentDidMount` will not be called,
only `componentDidUpdate`.

From react docs, on `componentDidUpdate()`:
"Use this as an opportunity to operate on the DOM when the component has been updated."

**Comment by shlomitc** [comment]
But why would you like the data-hook after it has been set?

**Comment by hepiyellow** [comment]
1. So you agree that this could be an issue?
2. I am not a prophet. User have their own crazy ideas, its out of our hands. The semantics of data-hook as a unique ID is just a guide-line.
3. Theoretically, it could be that 2 siblings are rendered with different data-hooks. Then the first one is removed (parent component renders only the second item), and React decides to update the first sibling's DOM element and remove the second sibling's DOM element.

**Comment by shlomitc** [comment]
1. maybe :)
2. ok
3. did you encounter this use case? if so, I'll be happy to see it

**Comment by hepiyellow** [comment]
About (3.): I was wrong...     BUT !
About (2.): Here is a very sensible (not crazy) example where `dataHook` will fail. 
I call it the "list-pagination-with-item-IDs-as-data-hooks" example.

- Someone could decide to use the `data-hook` as an itemID (some applicative ID, not a UI id).
- Then build a component which displays k items from a list of n items, and lets you "paginate" through the list (by increasing the startIndex of the items which are shown).

Here is a code example ( I wrote it as a test in `wix-ui-core`):
```ts
it.only('should set new data-hook value when updated', async () => {
      const HOCComponent = createHOC(ChildComponent);

      class Parent extends React.Component<{itemIds: number[]}, {startIndex: number}> {
        startIndex: number;

        constructor(props) {
          super(props);
          this.state = {startIndex: 0};
        }

        render() {
          return (
            <div onClick={() => this.setState({startIndex: this.state.startIndex + 1})}>
              <HOCComponent dataHook={`item-${this.props.itemIds[this.state.startIndex]}`} />
              <HOCComponent dataHook={`item-${this.props.itemIds[this.state.startIndex + 1]}`} />
            </div>
          );
        }
      }
      const wrapper = render(<Parent itemIds={[10, 20, 30, 40]}/>);
      expect(wrapper.find('ChildComponent').length).toBe(2);
      const childWrapper1 = () => wrapper.find('ChildComponent').at(0);
      const childWrapper2 = () => wrapper.find('ChildComponent').at(1);
      const parentWrapper = wrapper.find('Parent');
      expect(parentWrapper.length).toBe(1);
      expect(childWrapper1().getDOMNode().getAttribute('data-hook')).toBe('item-10');
      expect(childWrapper2().getDOMNode().getAttribute('data-hook')).toBe('item-20');
      parentWrapper.simulate('click');
      expect(parentWrapper.instance().state.startIndex).toBe(1);
      expect(childWrapper1().getDOMNode().getAttribute('data-hook')).toBe('item-20');
      expect(childWrapper2().getDOMNode().getAttribute('data-hook')).toBe('item-30');
    });
```

**Comment by lbelinsk** [comment]
I think it is perfectly fine to say that we don't support data-hook updates. If Automation team wouldn't count on these data-hooks, We would have been removing them from production (active only in dev env) anyway.

Since it is in production, having some kind of condition related running on each prop update is too expensive.

IMO, if even if this rare scenario is problematic, I prefer waiting for someone to complain since it is not a production risk.

**Comment by hepiyellow** [comment]
If we don’t support it, we should throw an error.
