### ISSUE TITLE
wix-storybook-utils: AutoExample - add ability to reset focus

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#347]
for focus e2e tests, we need to be able to reset the focus between tests.
Preferably using autoExampleDriver.reset().

The reset() should include reseting the document's activeElement in such a way so that when pressing TAB one time, then the tested component would be focusable.

This could be achieved by putting a focusable element (e.g. `div` with `tabindex=0`) BEFORE the tested component , and focusing on that div when making a `reset()`.

While at it, it would be useful to have another focusable element AFTER the tested component.

A generic implementation may be to add to the story config, 2 properties: `renderBefore` and `renderAfter`.

If we think it is generic enough, we can add those focusable elements to the AutoExample as built in (wither alwaysm or optional), that way the `autoExampleDriver.reset()` could also take care of reseting the focus.

**Comment by hepiyellow** [comment]
@shlomitc FYI

**Comment by shlomitc** [comment]
I'm ok with adding another wrapping div as suggested, but I'm not sure what `renderBefore/After` means.

**Comment by hepiyellow** [comment]
I think the proper way to test focus and Tabbing, is not with a wrapping `div`,
but with a structure like this:
```
<body>
  <div tabindex=0 data-hook="focusable-header"/>
  <... our tested ... />
  <div tabindex=0 data-hook="focusable-footer"/>
</body>
```
So we can easily test TAB and SHIFT-TAB, reset the focus to the "focusable-header".

**Comment by argshook** [comment]
closed by https://github.com/wix/wix-ui/pull/674

`autoexampleDriver.reset` has a new friend  `autoexampleDriver.remount` which, as name suggests, remounts the component. remount means that component is momentarily removed and readded to the DOM which results in fresh state.
