### ISSUE TITLE
wix-storybook-utils: AutoStory gets error when propTypes has a dynamic prop name.

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#367]
when that happens, I am getting this error when building the story.
```
webpack building...
 50% building modules 2/3 modules 1 active ...eact/stories/Button/standard.story.jsERROR: Unable to handle composed props Error: No suitable component definition found.
```

**Comment by shlomitc** [comment]
@hepiyellow -  is this still happening?

**Comment by argshook** [comment]
at the moment standard button story works well so i'm assuming all is good https://wix-wix-style-react.surge.sh/?selectedKind=5.%20Buttons&selectedStory=5.1%20Standard&full=0&addons=0&stories=1&panelRight=0

please reopen if you still see this issue
