### ISSUE TITLE
ToggleSwitch

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-ui#38]
- [x] Create composite of toggle & label
- [x] UX definition in focus state
- [x] check whether keycode should be replaced by key
- [x]  toggleSwitch has it’s own state (in html element input), even without onChange handler it toggles.
- [x] RTL
- [x] Get icon as prop, not hardcoded "V" and "-"
- [x] Instead of having size=oneOf([‘x-small’, ‘small’, ‘large’]) we would like to have oneOf([‘small’, ‘medium’, ‘large’]). This is a breaking change and in wix-style-react we should create an adapter for it, to make sure this breaking change will be invisible to the users
- [x] correct dependency of [selenium-webdriver](https://github.com/wix/wix-ui/pull/89/files#diff-709087c4e48467c0cc21fcbc15453192R5)

**Comment by Wo1v3r** [comment]
**PRs:**
Make ToggleSwitch accessible #89  Check the blue border when focused is good with UX
 toggleSwitch has it’s own state (in html element input), even without onChange handler it toggles. #122

**Comment by shlomitc** [comment]
I think it's all done
