### ISSUE TITLE
wix-storybook-utils: would we add version in the storybook

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#392]
Meaning that for example in the top left corner, where the title of the storybook is (e.g. `WIX-STYLE-REACT`) it will state the release version, such as `3.1.1`.

**Comment by argshook** [comment]
Closing old issue.

Displaying version can be done by importing package.json and passing version through storybook configs, as done in wix-style-react.

So no need for wix-storybook-utils
