### ISSUE TITLE
AutoStory has `<index/>` instead of component's name (WUB: UIText, Button, Label)

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#448]
See https://github.com/wix/wix-ui-backoffice/pull/77

Aijus wrote:

> `index` may be shown when react-docgen-typescript cant find displayName ('cause reasons) and so it then falls back on file name. i'll go over these issues, i have a card on leankit :)

Also happens for `<Button>` which extends the core's `Button` which does have a displayName and is an SFC.

For comparison, I looked at Checkbox which does have a proper tag name in the storybook.
`<Checkboxk>` doesn't have a displayName, but is a class (not an SFC).

So I think the issue is with SFC.

**Comment by argshook** [comment]
@shlomitc please see my comment here https://github.com/wix/wix-ui-backoffice/pull/77#issuecomment-385877182

**Comment by argshook** [comment]
many of these issues were solved by PRing third party and adding `displayName` on our side.

In majority of cases when component name is wrong it's one of:
1. component is anonymous function (doesn't have a name)
2. after code transpiling compnent becomes anonymous function and name is lost
3. component is `export default class` which is also nameless

all these cases can be solved by explicitly defining `displayName`
