### ISSUE TITLE
AutoStory: setting defaultProps before propTypes breaks story

### ISSUE THREAD

**Issue by Zombiefruit** [wix/wix-ui#454]
Issue: setting `defaultProps` before `propTypes` breaks the story, and results in an ambiguous error. 

Example:
Using the VBox, if we set `defaultProps` and `propTypes` like so,

```
VBox.defaultProps = defaultProps;

VBox.propTypes = {
  children: any,
  horizontalAlignment: oneOf(['left', 'center', 'right']),
  spacing: number
};
```

we get the following error in the story:

<img width="917" alt="screen shot 2018-04-30 at 13 37 27" src="https://user-images.githubusercontent.com/12984180/39423731-f5ad7076-4c7b-11e8-95e8-85dc566d0dde.png">

However, if we change the order of assignment to this,

```
VBox.propTypes = {
  children: any,
  horizontalAlignment: oneOf(['left', 'center', 'right']),
  spacing: number
};

VBox.defaultProps = defaultProps;
```
the story works as intended.

Scope: Tested and confirmed on HBox and VBox only.

**Comment by argshook** [comment]
oops, forgot to close this, it has been fixed https://github.com/wix/wix-ui/pull/453#issuecomment-386525912
