### ISSUE TITLE
AutoDocs - missing props in the playground

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#461]
Fore example, Popover - `placement` prop is missing from the `Usage` tab
https://wix.github.io/wix-ui/?selectedKind=Components&selectedStory=Popover&full=0&addons=0&stories=1&panelRight=0

**Comment by argshook** [comment]
no longer missing in current wix-ui-core storybook https://wix-wix-ui-core.surge.sh/?selectedKind=Components&selectedStory=Popover&full=0&addons=0&stories=1&panelRight=0
