### ISSUE TITLE
Enums aren't shown in the storybook

### ISSUE THREAD

**Issue by guybenron** [wix/wix-ui#482]
How will users know about the enum-ed props if they aren't displayed? :(

**Comment by hepiyellow** [comment]
Enums are displayed, see :
http://localhost:6006/?selectedKind=Internal&selectedStory=FloatingHelperContent&full=0&addons=0&stories=1&panelRight=0

Although there are some missing feature related to enums that are needed to make it usable.

See https://github.com/wix/wix-ui/issues/525

Closing this one
