### ISSUE TITLE
AutoExample - propDefaults - when prop input is cleared the the default prop value should be set

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#483]
If for example a string prop, has a default value, and the AutoExample has an <Input> where you can specify it.

The issue:
 if you type something in the <input> and clear it, then the prop now gets undefined instead of the default value. which is not a valid state of the component.

Solution:
The <Input>  should show the default value as a placeholder. When text is typed and cleared, the prop should be set to the default value (and placeholder text appears).

Same for other type of props.

**Comment by argshook** [comment]
placeholder value for string type props are already shown

clearing value and setting it to default would maybe make sense for required props. otherwise it's valid.

**Comment by argshook** [comment]
closing, similar to #931
