### ISSUE TITLE
AutoDocs - property description can not include `<Something>`

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#506]
I have a property with this comment for description:
```
/** A <HelperContent> */
```

And all I get in the generated docs is:
```
 A 
```

See FloatingHelper's story , `content1 property in the API tab:
https://wix-wix-ui-backoffice.surge.sh/?selectedKind=Components&selectedStory=FloatingHelper&full=0&addons=0&stories=1&panelRight=0

**Comment by shlomitc** [comment]
It's just a markdown so it treats it as an html tag
![image](https://user-images.githubusercontent.com/6093192/40344645-6604ee02-5d9e-11e8-8b0e-64e7af07f1e9.png)

try escaping the value

**Comment by argshook** [comment]
closing, it is simply markdown and i see comment was fixed
