### ISSUE TITLE
teamcity-surge-autorelease breaks usage outside of Wix

### ISSUE THREAD

**Issue by AviVahl** [wix/wix-ui#524]
@shlomitc we can't use closed packages in an open source project. It breaks for anyone outside of Wix.

```
$ mkdir newproject
$ cd newproject/
$ yarn init -y
$ yarn add wix-ui-core
yarn add v1.7.0
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "teamcity-surge-autorelease" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by idoros** [comment]
@shlomitc @nadavov @shahata - this basically means that this project is **not open source** as you cannot install it if you are not part of Wix!

**Comment by wilomgfx** [comment]
Pretty sad, `wix-storybook-utils` is an amazing addon to storybook, the whole community would benefit from this addon.

**Comment by wilomgfx** [comment]
Installing with `npm` fixed it. `Yarn` does not seem to skip `optional-dependencies` correctly.

https://github.com/yarnpkg/yarn/issues/2666

**Comment by shlomitc** [comment]
As this step is only for static files deployment, it is unnecessary for local development.
We can remove it from the optionalDependencies and run in scripts on demand `npx teamcity-surge-autorelease@^1.0.0`. WDYT?

**Comment by AviVahl** [comment]
Much better.

**Comment by lbelinsk** [comment]
We are now using the npx notation. There are no optional dependencies of the private surge-autorelease package. Closing the issue.

**Comment by wilomgfx** [comment]
awesome thank you @lbelinsk !
