### ISSUE TITLE
AutoDocs - parse error

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#546]
Getting erros like `Cannot read property 'skin' of undefined` in browser when accesing story (Backoffice, Button).

- The error comes from AutoExample.render()
- In AutoExample.render(), the `this.parsedComponent` is:
```
{readme: "", readmeAccessibility: "", readmeTestkit: "", displayName: undefined}
```
 which seems empty. So I assume there was some error during parsing of the source.

It would be better to have a more informative error, saying that parsing of the component source failed. And maybe tell us what failed.

I encounter these AutoExample errors are very often, and it is frustrating to debug and understand it.

PS: This happens locally, still not in Backoffice published storybook.

**Comment by shlomitc** [comment]
still relevant?

**Comment by argshook** [comment]
this specific issue is now resolved, but errors is something to be worked on.

closing.
