### ISSUE TITLE
AutoDocs - API tab -props missing when using Pick / Omit

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#550]
props missing when:
- Typescript: the component's props interface use type which is built from:
  -  `Pick<>` 
  - `Omit<>` (using Omit from [type-zoo](https://github.com/pelotom/type-zoo))
- Javascript: component's props spread `propTypes` using Lodash `pick`/`omit`

**Comment by argshook** [comment]
react-docgen parses javascript components, relevant issue https://github.com/reactjs/react-docgen/issues/283

**Comment by argshook** [comment]
we prefer not to do omit or pick thing, it's hard for machine to understand and so it's hard for the human to understand also.

closing.

**Comment by hepiyellow** [comment]
Please add to contribution guidelines of WSR and Wix-ui
To not use pick and omit with proptypes if Props interface.
