### ISSUE TITLE
AutoDocs - props comments do not support jsdoc {@link}

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#551]
See http://usejsdoc.org/tags-inline-link.html

If I put this in the comment of the prop:
`/**  [PopperJs]{@link https://popper.js.org/popper-documentation.html#modifiers..preventOverflow.boundariesElement} */`

It doesn't work. put the string as it is.

I guess it should support all jsdoc features.
If a {@deprecated} is present, then it should show the whole prop with strikethrough or something like that.

**Comment by argshook** [comment]
it currently supports markdown which allows you to do links `[like](this)`
