### ISSUE TITLE
wix-ui-core: Popover.driver - expose content text

### ISSUE THREAD

**Issue by bchmn** [wix/wix-ui#578]
Popover driver currently has a `getContentElement` method that returns the contents inner HTML, problem with this is that the content HTML structure isn't consistent so there's no way for a consumer of the driver to get the textual content.

1. Add a `data-hook` to the popover content element
2. Add a `getContent` method to the driver which uses the popover content element data-hook and returns the text.

**Comment by alisey** [comment]
By the looks of it `getContentElement` doesn't return `innerHTML`, it returns an `Element | undefined` (incorrect type definition, should be `HTMLElement | null`), and you get `innerHTML` or `textContent` or `childNodes` from it. Are we talking about the same [method](https://github.com/wix/wix-ui/blob/4ff679700d7ebf75c6aca0ae9a72db7b3b825b72/packages/wix-ui-core/src/components/Popover/Popover.driver.ts#L9)?

**Comment by shlomitc** [comment]
content is passed by the consumer of the component, meaning you can easily set a data-hook on the content by yourself, and query for it in the DOM after displaying the component
