### ISSUE TITLE
Auto documentation tools

### ISSUE THREAD

**Issue by argshook** [wix/wix-ui#60]
This is a container issue to collect insights and document migration leftovers

**status quo**: wix-storybook-utils exposes `story()` which works during runtime
**the plan**: change approach so that `story()` does its job during buildtime

Steps to be done after buildtime tooling is done:

1. check if `src` is still needed to be included in node module (from #55)
1. remove `src` from `wix-storybook-utils/package.json` files section and expose only autoexample driver. (https://github.com/wix/wix-style-react/issues/1267)

**Comment by shlomitc** [comment]
any new thoughts regarding this?

**Comment by argshook** [comment]
can be closed. `src` at the moment is still required
