### ISSUE TITLE
AutoDocs - TypeError when prop has defaultProp but not propTypes

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#617]
I am not sure if it is a valid React thing to do.
But I had a component with : 
```
Component.defaultProps = {
  children: <div/>
}
Component.proptypes = {
  someOtherProp: bool
  // children has no prop type
}
```

AutoDocs gets a TypeError  on this line:
https://github.com/wix/wix-ui/blob/16c7e017ac4bf2e77b96a3f678cadcdca0169591/packages/wix-storybook-utils/src/AutoExample/index.js#L287

`type` is undefined.

I think AutoDocs should throw an error when parsing the file, when it creates a parsedProp that doesn't have a type. And give an informational error.

Is there a way to recover from this error, (if this is a valid situation)?

**Comment by argshook** [comment]
hey, could you show me where this happens? i'd like to see what prop fails where and if maybe there's a mixup in autoexample with defaultProps, propTypes and parsed props. in general `this.parsedComponent.props[prop]` should always have `type` so im interested when that's not the case

**Comment by argshook** [comment]
ping, does it still happen? if yes, can you show me where?

**Comment by argshook** [comment]
closing, i'm guessing the issue was `Component.proptypes` (lowercase `t` in `proptypes`)
