### ISSUE TITLE
AutoExample - Add QA tool

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#626]
# Background
AutoExample is a lot of times used as a manual QA tool, or issue investigation tool.
When playing with  props in the playground, it always does a component re-render (update).

# Suggestion
In some cases we would like to have the component re-mount (not re-render).
- That gives us an easy way to look at how the component behaves in a re-mount, verifying that it unmounts properly.
- In many cases, our component don't support well re-render of some props (usually props which are not expected to ever be changed during the lifetime of a component). Although this is a case of a component malfunction, and should be fixed, we could have an easy way of bypassing that if re-mounting is sufficient for our purpose.

# Error handling
For some reason some component errors are not recoverable, meaning that auto-example stops re-rendering and  a page reload page is needed.
This might be a separate issue that needs to be handled. But while it isn't, having a re-mount option would help.

# Suggested design
Add a "toolbar" to the Playground, with:
- "Auto-Apply" checkbox - when checked then any change in a prop would be "submitted". 
- "Re-mount/Re-render" toggle: when a prop change is submitted, this controls wether a re-render or re-mount will occur.
- "Submit" - button

**Comment by argshook** [comment]
closing, remount button was added some time ago in the playground
