### ISSUE TITLE
`wix-ui-icons-common` contains `teamcity-surge-autorelease`

### ISSUE THREAD

**Issue by rghorbani** [wix/wix-ui#732]
It appears that latest version of [`wix-ui-icons-common`](https://www.npmjs.com/package/wix-ui-icons-common) (2.0.14, 2.0.13) contains `teamcity-surge-autorelease` which is as it seems is one of wix's internal packages.

**Comment by shlomitc** [comment]
I just released version 2.0.15 which contains it as a dev-dependency.
please let me know if it's still preventing you from installing

**Comment by shlomitc** [comment]
just to be on the safe side, just release 2.0.16 which doesn't include it as a dependency at all

**Comment by rghorbani** [comment]
Just tested it. Everything seems to be fine now.
Thank you.
