### ISSUE TITLE
wix-ui-core: `<Popover/>` - componentDidUpdate does not update portal node

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#762]
I think the title is quite descriptive.

I think we need to call `applyStylesToPortaledNode` in `componentDidUpdate`

### Example
See FloatingHelper's story (`wix-ui-backoffice`), with the new `appearance` property.
https://wix-wix-ui-backoffice-pr-218.surge.sh/?selectedKind=Components&selectedStory=FloatingHelper&full=0&addons=0&stories=1&panelRight=0

When switching to `light` appearance, the `data-appearance` attribute on the portal node is still `dark`.

**Comment by yardnsm** [comment]
Resolved in https://github.com/wix/wix-ui/pull/902
