### ISSUE TITLE
`button-next` - something is weird with disabled state

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#771]
- The `disabled` prop does not add an HTML `disabled` attributeon `<button>`
- So The `.root:disabled` rule in `button-next.st.css` will never apply.
- If we will add `disabled` HTML attribute to `<button>`, then we don't need this `onClick={disabled ? null : onClick}`

## Do we want to add a `disabled` Stylable state?
It seems redundant, since consumer can target the native attribute `.root[disabled]`.
But adding a `disabled` Stylable state would be forward compatible with any crazy changes we would make in the component's DOM structure.

@mykas You worked on button-next, can you take a look.
@shlomitc What do you think?

**Comment by mykas** [comment]
I think it is a bug in buttonNext. I did not pass disabled state to `button-next.st.css`. But if we gonna have HTML attribute for <button> will this `onClick={disabled ? null : onClick}` be by default?

**Comment by mykas** [comment]
I think we have `disabled` html prop by default. I am just not sure if we need to pass it to stylable state object.
