### ISSUE TITLE
DropDown emits React deprecation warnings

### ISSUE THREAD

**Issue by tompere** [wix/wix-ui#996]
Using `DropDown` component in React 16.5.x strict mode, throws console warnings:

```
componentWillMount: Please update the following components to use componentDidMount instead: Dropdown

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Dropdown
```

**Comment by shlomitc** [comment]
we still want the dropdown to support React 15 without errors, so we're using React 16.4.

**Comment by tompere** [comment]
@shlomitc do u mean that wix-ui will remain on react 16.x for the upcoming future?
what about using https://github.com/reactjs/react-lifecycles-compat

**Comment by shlomitc** [comment]
Yes, we can consider it, but it's not prioritized at the moment.
If you wish to contribute, I'll be happy for a PR

**Comment by tompere** [comment]
@eranshabi is working on a PR

**Comment by shlomitc** [comment]
fixed
